import { BookBuilder } from '../bookBuilder';
import type { Book } from '../../book/schema';

/** Long climb all the way into Space, resolves 1,000x. PROTOTYPE_V1.md §5 fixture 9. */
export const spaceRun1000x: Book = new BookBuilder()
  .towerStart('spaceRun', 'exceptional', 999)
  .block({ behavior: 'clean' })
  .block({ behavior: 'offset', offsetU: 600, rotationMd: 550, direction: 1 })
  .block({ behavior: 'clean' })
  .zoneChange('skyline')
  .block({ behavior: 'clean' })
  .block({ behavior: 'clean' })
  .block({ behavior: 'wobble', offsetU: -750, rotationMd: -700, direction: -1, intensity: 2 })
  .block({ behavior: 'clean' })
  .zoneChange('sky')
  .block({ behavior: 'clean' })
  .block({ behavior: 'clean' })
  .block({ behavior: 'offset', offsetU: 650, rotationMd: 600, direction: 1 })
  .block({ behavior: 'clean' })
  .zoneChange('atmosphere')
  .block({ behavior: 'clean' })
  .block({ behavior: 'wobble', offsetU: -800, rotationMd: -750, direction: -1, intensity: 3 })
  .block({ behavior: 'clean' })
  .block({ behavior: 'clean' })
  .zoneChange('space')
  .block({ behavior: 'clean' })
  .block({ behavior: 'clean' })
  .block({ behavior: 'nearFall', offsetU: 1500, rotationMd: 1600, direction: 1, intensity: 4 })
  .block({ behavior: 'clean' })
  .survive(3)
  .setWin(100000)
  .setTotalWin(100000)
  .finalWin(100000)
  .build(9, 100000, 'space-run-1000x');
